server:
  port: 8012

spring:
  jackson:
    time-zone: GMT+8
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/zxw?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 100MB

mybatis:
  config-location: classpath:config/mybatis.xml
  mapper-locations: mybatis/**/**/*.xml
  type-aliases-package: com.admin.web.**.**.entity

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
